service: s3-notification # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
 include:
   - mailer/**

functions:
  s3_notification:
    handler: handler.s3_notification
    events:
      - s3:
          bucket: s3-jmo
          event: s3:ObjectCreated:*